<?php

namespace Microscrap\Bindings\CUDA\Enums;

/**
 * CUDA Runtime error codes (cudaError_t) commonly used with ext-cuda.
 *
 * Values match CUDA Toolkit headers. Pass `$error->value` (or the raw int)
 * into cudaGetErrorString / cudaGetErrorName.
 */
enum CudaError: int
{
    case CUDA_SUCCESS = 0;
    case CUDA_ERROR_INVALID_VALUE = 1;
    case CUDA_ERROR_MEMORY_ALLOCATION = 2;
    case CUDA_ERROR_INITIALIZATION_ERROR = 3;
    case CUDA_ERROR_CUDART_UNLOADING = 4;
    case CUDA_ERROR_PROFILER_DISABLED = 5;
    case CUDA_ERROR_PROFILER_NOT_INITIALIZED = 6;
    case CUDA_ERROR_PROFILER_ALREADY_STARTED = 7;
    case CUDA_ERROR_PROFILER_ALREADY_STOPPED = 8;
    case CUDA_ERROR_INVALID_CONFIGURATION = 9;
    case CUDA_ERROR_INVALID_PITCH_VALUE = 12;
    case CUDA_ERROR_INVALID_SYMBOL = 13;
    case CUDA_ERROR_INVALID_DEVICE_POINTER = 17;
    case CUDA_ERROR_INVALID_MEMCPY_DIRECTION = 21;
    case CUDA_ERROR_INSUFFICIENT_DRIVER = 35;
    case CUDA_ERROR_MISSING_CONFIGURATION = 52;
    case CUDA_ERROR_PRIOR_LAUNCH_FAILURE = 53;
    case CUDA_ERROR_INVALID_DEVICE_FUNCTION = 98;
    case CUDA_ERROR_NO_DEVICE = 100;
    case CUDA_ERROR_INVALID_DEVICE = 101;
    case CUDA_ERROR_DEVICE_NOT_LICENSED = 102;
    case CUDA_ERROR_INVALID_IMAGE = 200;
    case CUDA_ERROR_INVALID_CONTEXT = 201;
    case CUDA_ERROR_CONTEXT_ALREADY_CURRENT = 202;
    case CUDA_ERROR_MAP_FAILED = 205;
    case CUDA_ERROR_UNMAP_FAILED = 206;
    case CUDA_ERROR_ARRAY_IS_MAPPED = 207;
    case CUDA_ERROR_ALREADY_MAPPED = 208;
    case CUDA_ERROR_NO_BINARY_FOR_GPU = 209;
    case CUDA_ERROR_ALREADY_ACQUIRED = 210;
    case CUDA_ERROR_NOT_MAPPED = 211;
    case CUDA_ERROR_NOT_MAPPED_AS_ARRAY = 212;
    case CUDA_ERROR_NOT_MAPPED_AS_POINTER = 213;
    case CUDA_ERROR_ECC_UNCORRECTABLE = 214;
    case CUDA_ERROR_UNSUPPORTED_LIMIT = 215;
    case CUDA_ERROR_CONTEXT_ALREADY_IN_USE = 216;
    case CUDA_ERROR_PEER_ACCESS_UNSUPPORTED = 217;
    case CUDA_ERROR_INVALID_PTX = 218;
    case CUDA_ERROR_INVALID_GRAPHICS_CONTEXT = 219;
    case CUDA_ERROR_NVLINK_UNCORRECTABLE = 220;
    case CUDA_ERROR_JIT_COMPILER_NOT_FOUND = 221;
    case CUDA_ERROR_INVALID_SOURCE = 300;
    case CUDA_ERROR_FILE_NOT_FOUND = 301;
    case CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND = 302;
    case CUDA_ERROR_SHARED_OBJECT_INIT_FAILED = 303;
    case CUDA_ERROR_OPERATING_SYSTEM = 304;
    case CUDA_ERROR_INVALID_HANDLE = 400;
    case CUDA_ERROR_ILLEGAL_STATE = 401;
    case CUDA_ERROR_NOT_FOUND = 500;
    case CUDA_ERROR_NOT_READY = 600;
    case CUDA_ERROR_ILLEGAL_ADDRESS = 700;
    case CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES = 701;
    case CUDA_ERROR_LAUNCH_TIMEOUT = 702;
    case CUDA_ERROR_LAUNCH_FAILURE = 719;
    case CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE = 720;
    case CUDA_ERROR_NOT_PERMITTED = 800;
    case CUDA_ERROR_NOT_SUPPORTED = 801;
    case CUDA_ERROR_SYSTEM_NOT_READY = 802;
    case CUDA_ERROR_SYSTEM_DRIVER_MISMATCH = 803;
    case CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE = 804;
    case CUDA_ERROR_MPS_CONNECTION_FAILED = 805;
    case CUDA_ERROR_MPS_RPC_FAILURE = 806;
    case CUDA_ERROR_MPS_SERVER_NOT_READY = 807;
    case CUDA_ERROR_MPS_MAX_CLIENTS_REACHED = 808;
    case CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED = 809;
    case CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED = 900;
    case CUDA_ERROR_STREAM_CAPTURE_INVALIDATED = 901;
    case CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD = 906;
    case CUDA_ERROR_UNKNOWN = 999;
}
